// Autogenerated from CSharpBinding.addin.xml

using System.Reflection;

[assembly: AssemblyProduct ("MonoDevelop")]
[assembly: AssemblyTitle ("PlayScript Language Binding")]
[assembly: AssemblyDescription ("PlayScript Language Binding")]
[assembly: AssemblyVersion ("2.6")]
[assembly: AssemblyCopyright ("MIT X11")]
